name: Dart-App-Demo
version: 1.0.0
schema: v1
models:
  - name: gemini-model
    provider: gemini
    model: gemini-3.5-flash
    apiBase: https://generativelanguage.googleapis.com/v1beta
    apiKey: ${{ secrets.GOOGLE_API_KEY }}
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 1500
    rules:
      - 日本語で答えてください
context:
  - provider: file
  - provider: code
  - provider: diff
  # - provider: terminal
  
